apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{ template "hello-world.release_labels" . }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
